name: Lint and test

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: [self-hosted]
    env:
      HBT_JOB_ID: ${{ github.run_number }}_${{ github.run_id }}_${{ github.run_attempt }}_lint
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.HBT_JOB_ID }}
    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@master
        with:
          persist-credentials: false
          submodules: recursive
          path: ${{ env.HBT_JOB_ID }}

      - name: Install dependencies ☕️
        run: |
          source setup.sh ""

      - name: Lint 🔍
        run: |
          source setup.sh ""
          ./tests/run_linting

      - name: Cleanup 🧹
        if: always()
        run: |
          cd ..
          rm -rf "${HBT_JOB_ID}"
